// Choice Legacy product catalogue

const choiceLegacyProducts = [
  {
    id: 101,
    store: 'choice-legacy',
    brand: 'L\'Oréal Paris',
    name: 'Revitalift Laser Pure Retinol Serum',
    category: 'Skincare',
    currentPrice: 2800,
    originalPrice: 3200,
    discount: 13,
    rating: 4.7,
    reviews: 284,
    badge: 'Bestseller',
    cashback: 80,
    coupon: 'CL10',
    imageEmoji: '💜',
    inStock: true,
  },
  {
    id: 102,
    store: 'choice-legacy',
    brand: 'Maybelline',
    name: 'Fit Me Matte + Poreless Foundation',
    category: 'Makeup',
    currentPrice: 950,
    originalPrice: 1100,
    discount: 14,
    rating: 4.5,
    reviews: 512,
    badge: 'Popular',
    cashback: 30,
    coupon: '',
    imageEmoji: '💄',
    inStock: true,
  },
  {
    id: 103,
    store: 'choice-legacy',
    brand: 'Dove',
    name: 'Intensive Repair Shampoo 700ml',
    category: 'Haircare',
    currentPrice: 650,
    originalPrice: 750,
    discount: 13,
    rating: 4.6,
    reviews: 378,
    badge: 'Offer',
    cashback: 0,
    coupon: 'HAIR15',
    imageEmoji: '💁',
    inStock: true,
  },
  {
    id: 104,
    store: 'choice-legacy',
    brand: 'Neutrogena',
    name: 'Hydro Boost Water Gel Moisturizer',
    category: 'Skincare',
    currentPrice: 1750,
    originalPrice: 2000,
    discount: 13,
    rating: 4.8,
    reviews: 467,
    badge: 'Doctor Pick',
    cashback: 50,
    coupon: '',
    imageEmoji: '💧',
    inStock: true,
  },
  {
    id: 105,
    store: 'choice-legacy',
    brand: 'Garnier',
    name: 'Bright Complete Vitamin C Serum',
    category: 'Skincare',
    currentPrice: 580,
    originalPrice: 680,
    discount: 15,
    rating: 4.4,
    reviews: 623,
    badge: 'New',
    cashback: 20,
    coupon: 'GLOW20',
    imageEmoji: '✨',
    inStock: true,
  },
  {
    id: 106,
    store: 'choice-legacy',
    brand: 'The Body Shop',
    name: 'Vitamin E Moisture Cream 50ml',
    category: 'Body Care',
    currentPrice: 1450,
    originalPrice: 1700,
    discount: 15,
    rating: 4.7,
    reviews: 219,
    badge: 'Premium',
    cashback: 60,
    coupon: '',
    imageEmoji: '🌿',
    inStock: true,
  },
  {
    id: 107,
    store: 'choice-legacy',
    brand: 'Pantene',
    name: 'Pro-V Silky Smooth Care Conditioner 360ml',
    category: 'Haircare',
    currentPrice: 480,
    originalPrice: 560,
    discount: 14,
    rating: 4.5,
    reviews: 445,
    badge: '',
    cashback: 0,
    coupon: '',
    imageEmoji: '🌊',
    inStock: true,
  },
  {
    id: 108,
    store: 'choice-legacy',
    brand: 'Nivea',
    name: 'Total Face Cleanup Face Wash',
    category: 'Skincare',
    currentPrice: 320,
    originalPrice: 380,
    discount: 16,
    rating: 4.3,
    reviews: 729,
    badge: 'Sale',
    cashback: 0,
    coupon: '',
    imageEmoji: '🫧',
    inStock: true,
  },
]

module.exports = choiceLegacyProducts
