// Kirei product catalogue — mirrors the frontend data so the API
// returns real product objects the React pages can consume.

const kireiProducts = [
  {
    id: 1,
    store: 'kirei',
    brand: 'COSRX',
    name: 'Advanced Snail 96 Mucin Power Essence',
    category: 'K-Beauty',
    currentPrice: 1850,
    originalPrice: 2200,
    discount: 16,
    rating: 4.8,
    reviews: 312,
    badge: 'Bestseller',
    cashback: 50,
    coupon: 'KIREI10',
    imageEmoji: '✨',
    inStock: true,
  },
  {
    id: 2,
    store: 'kirei',
    brand: 'Hada Labo',
    name: 'Gokujyun Ultimate Moisturizing Lotion',
    category: 'J-Beauty',
    currentPrice: 1450,
    originalPrice: 1700,
    discount: 15,
    rating: 4.9,
    reviews: 489,
    badge: 'J-Beauty Pick',
    cashback: 0,
    coupon: '',
    imageEmoji: '🌸',
    inStock: true,
  },
  {
    id: 3,
    store: 'kirei',
    brand: 'Some By Mi',
    name: 'AHA BHA PHA 30 Days Miracle Toner',
    category: 'K-Beauty',
    currentPrice: 1250,
    originalPrice: 1500,
    discount: 17,
    rating: 4.7,
    reviews: 267,
    badge: 'New',
    cashback: 30,
    coupon: '',
    imageEmoji: '💧',
    inStock: true,
  },
  {
    id: 4,
    store: 'kirei',
    brand: 'Cetaphil',
    name: 'Gentle Skin Cleanser for Sensitive Skin',
    category: 'Doctor Cosmetics',
    currentPrice: 950,
    originalPrice: 1100,
    discount: 14,
    rating: 4.9,
    reviews: 621,
    badge: 'Doctor Pick',
    cashback: 0,
    coupon: 'DOCTOR5',
    imageEmoji: '🩺',
    inStock: true,
  },
  {
    id: 5,
    store: 'kirei',
    brand: 'Innisfree',
    name: 'Green Tea Seed Hyaluronic Serum',
    category: 'K-Beauty',
    currentPrice: 2100,
    originalPrice: 2500,
    discount: 16,
    rating: 4.6,
    reviews: 198,
    badge: 'Sale',
    cashback: 100,
    coupon: '',
    imageEmoji: '🍃',
    inStock: true,
  },
  {
    id: 6,
    store: 'kirei',
    brand: 'SK-II',
    name: 'Facial Treatment Essence (75ml)',
    category: 'J-Beauty',
    currentPrice: 5800,
    originalPrice: 6500,
    discount: 11,
    rating: 4.8,
    reviews: 143,
    badge: 'Premium',
    cashback: 200,
    coupon: 'SKII15',
    imageEmoji: '👑',
    inStock: true,
  },
  {
    id: 7,
    store: 'kirei',
    brand: 'Biore',
    name: 'UV Aqua Rich Watery Essence SPF50+',
    category: 'J-Beauty',
    currentPrice: 1100,
    originalPrice: 1350,
    discount: 19,
    rating: 4.7,
    reviews: 334,
    badge: 'SPF Fave',
    cashback: 0,
    coupon: '',
    imageEmoji: '☀️',
    inStock: true,
  },
  {
    id: 8,
    store: 'kirei',
    brand: "Johnson's",
    name: 'Baby Moisturising Lotion with Milk Proteins',
    category: 'Baby Care',
    currentPrice: 420,
    originalPrice: 500,
    discount: 16,
    rating: 4.9,
    reviews: 892,
    badge: 'Baby Safe',
    cashback: 0,
    coupon: '',
    imageEmoji: '🍼',
    inStock: true,
  },
]

module.exports = kireiProducts
